version: '3.9'
# 网络配置
networks:
  net-app:

services:
  # nginx服务
  nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
        - "${VARNISH_BACKEND_PORT}:81"
      container_name: "nginx"
      restart: always
      depends_on:
        - php-fpm
      networks:
        - net-app
  # #php-fpm服务
  php-fpm:
    build: 
      context: ./php
      args:
        - PHP_FPM_VERSION=${PHP_VERSION}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        - http_proxy
        - https_proxy
        - no_proxy
    container_name: "php-fpm"
    restart: always
    networks:
      - net-app
    volumes:
      - ./php/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    depends_on:
      - mysql
      - redis
    ports:
      - "${PHP_FPM_PORT}:9000"
      
  #mysql服务
  mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - net-app
  #redis服务
  redis:
      build: ./redis
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
        - ${REDIS_CONFIG_PATH}/redis.conf:/usr/local/etc/redis/redis.conf
      container_name: "redis"
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - net-app

  #jenkins
  jenkins:
    image: jenkins/jenkins:2.319.3-lts
    container_name: "jenkins"
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data/:/var/jenkins_home/
  #rabbitmq
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    restart: always
    # hostname: myRabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root  #账号
      - RABBITMQ_DEFAULT_PASS=root  #密码
    networks:
        - net-app